baseURL: "/"
languageCode: "zh-cn"
defaultContentLanguage: "zh"
# 分页个数
paginate: 10
outputs:
  home: ["HTML", "JSON"]
# 文章目录的配置
markup:
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
# 相关文章的配置
related:
  includeNewer: false
  indices:
  - name: keywords
    weight: 100
  - name: date
    weight: 10
  threshold: 80
  toLower: false