baseURL: "/"
languageCode: "zh-cn"
defaultContentLanguage: "zh"
# 分页个数
paginate: 10
outputs:
  home: ["HTML", "JSON"]
# 相关文章的配置
related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: date
    weight: 10
  threshold: 80
  toLower: false
# markdown渲染，修改一个值也要全部拷出来
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
