zh:
  contentDir: "content/zh/"
  languageName: "简体中文"
  title: "RadonDB 开源社区"
  weight: 10
  params:
    site_logo: "/images/radondb.svg"
    description: "一个面向云原生、容器化的数据库开源社区"
    kubesphereVideoPoster: "/images/intro-poster.png"
    kubesphereVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/%E5%A6%82%E4%BD%95%E5%9C%A8%20Kubernetes%20%E4%B8%8A%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL/%E5%B8%A6BGM/%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL%20%E9%9B%86%E7%BE%A4.mp4"
    # 关于我们页面中video的封面
    aboutVideoPoster: "/images/video.png"
    aboutVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/RadonDB%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D.mp4"
    show_popup: true
    popup_title: "新版试用赢周边！"
    popup_description: "RadonDB MySQL Kubernetes 2.2.0 发布，抢先试用新版本，领取精美社区周边"
    popup_link: "https://kubesphere.com.cn/forum/d/7623-radondb-mysql-kubernetes-220"
    popup_link_title: "抢先体验"

en:
  contentDir: "content/en/"
  languageName: "EN"
  title: "RadonDB OpenSource"
  weight: 20
  params:
    site_logo: "/images/radondb-en.png"
    description: "An open-source community for cloud native and database on Kubernetes"
    kubesphereVideoPoster: "/images/intro-poster.png"
    kubesphereVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/%E5%A6%82%E4%BD%95%E5%9C%A8%20Kubernetes%20%E4%B8%8A%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL/%E5%B8%A6BGM/%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL%20%E9%9B%86%E7%BE%A4.mp4"
    aboutVideoPoster: "/images/video.png"
    aboutVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/RadonDB%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D.mp4"
    show_popup: false
    popup_title: "Welcome to the Open Source Promotion Plan！"
    popup_description: "Open Source Promotion Plan aims to encourage students to actively participate in the development and maintenance of open source software and promote the vigorous development of excellent open source software community."
    popup_link: "/news/220505_%E5%BC%80%E6%BA%90%E4%B9%8B%E5%A4%8F-2022-%E9%87%8D%E7%A3%85%E6%9D%A5%E8%A2%AD%E6%AC%A2%E8%BF%8E%E6%8A%A5%E5%90%8D-radondb-%E7%A4%BE%E5%8C%BA%E9%A1%B9%E7%9B%AE/"
    popup_link_title: "查看详情"