# 主导航菜单
main:
  - identifier: projects
    name: "开源项目"
    weight: "1"
    url: "/projects"
  - name: "MySQL 容器化"
    weight: '1'
    url: "/projects/mysql"
    parent: projects
  - name: "Xenon 高可用集群组件"
    weight: '2'
    url: "/projects/xenon"
    parent: projects

  - identifier: docs
    name: "文档"
    weight: "1"
    url: "/docs"
  - identifier: /docs/mysql
    name: "MySQL 容器化"
    weight: '1'
    url: "/docs/mysql"
    parent: docs

  - name: "博客"
    url: "/posts"
    weight: "2"
  - name: "新闻"
    url: "/news"
    weight: "3"
  - name: "论坛"
    url: "https://kubesphere.com.cn/forum/t/RadonDB"
    weight: "4"
  - name: "关于我们"
    url: "/about"
    weight: "5"
