# 不需要多语言的参数配置
site_logo: "/images/radondb.svg"
favicon: "/radondb.ico"
# 首页第三行黑色背景的tag
radondb_projects:
  - MySQL
  - PostgreSQL
  - Redis
  - MongoDB
  - ClickHouse
  - ElesticSearch

# 全局弹窗
show_popup: false
popup_title: "MySQL 部署"
popup_description: "这里填描述"
popup_link: "/blog"