# 不需要多语言的参数配置
site_logo: "/images/radondb.svg"
favicon: "/radondb.ico"
# 首页第三行黑色背景的tag
radondb_projects:
  - MySQL
  - PostgreSQL
  - Redis
  - MongoDB
  - ClickHouse
  - ElesticSearch

# 全局弹窗
show_popup: true
popup_title: "开源之夏 2022 与您相约！"
popup_description: "开源之夏旨在鼓励在校学生积极参与开源软件的开发维护，促进优秀开源软件社区的蓬勃发展。"
popup_link: "https://jinshuju.net/f/O4yQHn"
popup_link_title: "申请成为导师"